name: "deploy"
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
      test_type:
        description: 'Type of test to run: smoke | load | stress | all'
        type: choice
        options:
          - smoke
          - load
          - stress
          - all
        default: 'smoke'
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: ${{ github.event.repository.name }}
      SECRET_NAME: ${{ vars.SECRET_NAME }}
      BUCKET_NAME: ${{ vars.BUCKET_NAME }}
      INSTANCE_ID: ${{ vars.INSTANCE_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 1. Autenticación con AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 2. Enviar comando SSM para ejecutar el script de despliegue y obtener secretos de AWS Secrets Manager
        env:
          PARAM_BRANCH: ${{ github.event.inputs.branch }}
          PARAM_TEST_TYPE: ${{ github.event.inputs.test_type }}
        run: |
          aws ssm send-command \
            --instance-ids ${{ vars.INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Despliegue de la aplicación" \
            --parameters 'commands=[
            "#!/bin/bash",
            "set -e",
            "mkdir -p /home/ec2-user/k6-results/${REPOSITORY_NAME}",
            "chown -R ec2-user:ec2-user /home/ec2-user/k6-results/${REPOSITORY_NAME}",
            "SECRET_NAME=$SECRET_NAME",
            "echo SECRET_NAME=$SECRET_NAME",
            "SECRETS=$(aws secretsmanager get-secret-value --secret-id ${SECRET_NAME} --query SecretString --output text --region us-east-1)",
            "echo \"$SECRETS\" | jq -r \"to_entries | .[] | \\\"\\(.key)=\\(.value)\\\"\" > /home/ec2-user/$REPOSITORY_NAME/.env",
            "cat /dev/null > /tmp/run-k6.sh",
            "echo '\''BUCKET_NAME='$BUCKET_NAME''\'' >> /tmp/run-k6.sh",
            "echo '\''TIMESTAMP=$(date +%Y%m%d-%H%M%S)'\'' >> /tmp/run-k6.sh",
            "echo '\''BRANCH=${PARAM_BRANCH}'\'' >> /tmp/run-k6.sh",
            "echo '\''TEST_TYPE=${PARAM_TEST_TYPE}'\'' >> /tmp/run-k6.sh",
            "echo '\''BASE_DIR=/home/ec2-user/'$REPOSITORY_NAME''\'' >> /tmp/run-k6.sh",
            "echo '\''RESULTS_DIR=/home/ec2-user/k6-results/${REPOSITORY_NAME}/${TEST_TYPE}/${TIMESTAMP}'\'' >> /tmp/run-k6.sh",
            "echo '\''S3_BASE=s3://${BUCKET_NAME}/${REPOSITORY_NAME}/${TEST_TYPE}/${TIMESTAMP}'\'' >> /tmp/run-k6.sh",
            "echo '\''cd ${BASE_DIR} && git pull origin ${BRANCH}'\'' >> /tmp/run-k6.sh",
            "echo '\''set -a'\'' >> /tmp/run-k6.sh",
            "echo '\''source ${BASE_DIR}/.env'\'' >> /tmp/run-k6.sh",
            "echo '\''set +a'\'' >> /tmp/run-k6.sh",
            "echo '\''run_tests() {'\'' >> /tmp/run-k6.sh",
            "echo '\''  local TYPE=$1'\'' >> /tmp/run-k6.sh",
            "echo '\''  echo \"Running tests of type: TEST_TYPE={TYPE}\"'\'' >> /tmp/run-k6.sh",
            "echo '\''  k6 run src/main.js -e TEST_TYPE={TYPE} --out csv=${RESULTS_DIR}/results-${TYPE}.csv --summary-export=${RESULTS_DIR}/summary-${TYPE}.json 2>&1 | tee ${RESULTS_DIR}/logs-${TYPE}.log'\'' >> /tmp/run-k6.sh",
            "echo '\''  aws s3 cp --recursive ${RESULTS_DIR}/ $S3_BASE/'\'' >> /tmp/run-k6.sh",
            "echo '\''  echo \"${TYPE} uploaded to S3\"'\'' >> /tmp/run-k6.sh",
            "echo '\''}'\'' >> /tmp/run-k6.sh",
            "echo '\''if [[ \"${TEST_TYPE}\" = \"all\" ]]; then'\'' >> /tmp/run-k6.sh",
            "echo '\''  run_tests smoke'\'' >> /tmp/run-k6.sh",
            "echo '\''  run_tests load'\'' >> /tmp/run-k6.sh",
            "echo '\''  run_tests stress'\'' >> /tmp/run-k6.sh",
            "echo '\''else'\'' >> /tmp/run-k6.sh",
            "echo '\''  run_tests ${TEST_TYPE}'\'' >> /tmp/run-k6.sh",
            "echo '\''fi'\'' >> /tmp/run-k6.sh",
            "echo '\''echo \"Todos los tests completados\"'\'' >> /tmp/run-k6.sh",
            "chmod +x /tmp/run-k6.sh",
            "chown ec2-user:ec2-user /tmp/run-k6.sh",
            "sudo -u ec2-user bash /tmp/run-k6.sh",
            "rm -f /tmp/run-k6.sh"
            ]'